# Project 2: Activities and Resting HR

In [3]:
%matplotlib inline
import numpy as np # linear algebra
import pandas as pd # pandas dataframe
import os
from glob import glob
import json
import matplotlib.pyplot as plt
import seaborn as sns
garmin_base_dir = "../files/Garmin_20241403/DI_CONNECT"

pd.set_option('display.max_columns', 500)

## Categories: running, swimming in pool, hiking, biking

In [4]:
#Running activities 
act_df = pd.read_csv("GarminActivities.csv")
act_df

,Unnamed: 0,VO2,Date,Km,Av_HR_for_Run,run_time,av_cadence
0,0,50.0,2024-05-04,10.02580,145.0,59.124067,174.671875
1,1,50.0,2024-05-02,8.04976,140.0,49.335650,171.328125
2,2,50.0,2024-04-30,5.86950,137.0,35.536633,175.281250
3,3,49.0,2024-04-28,6.81160,138.0,42.716883,175.906250
4,4,49.0,2024-04-26,9.13527,133.0,58.555600,172.281250
...,...,...,...,...,...,...,...
993,993,49.0,2020-11-26,9.01783,138.0,57.006750,183.703125
994,994,49.0,2020-11-25,13.10173,142.0,80.325300,184.406250
995,995,49.0,2020-11-23,4.40349,137.0,26.999217,187.765625
996,996,49.0,2020-11-22,11.34087,133.0,74.884784,182.812500
997,997,49.0,2020-11-21,12.03584,131.0,80.463650,182.609375

## What affects resting HR the most: running daily 12-13 km a week on average or running 4 times a week? (and swimming)

I only have running activities in the csv ... 

TODO: 
- How to use Garminconnect to download other activities such as:
    - Hiking (walking)
    - Biking
    - Swimming
    
- And which variables should be imported?
    - Date
    - Distance
    - Time